/**
 * Material Symbols (legacy) → Lucide icon name mapping.
 *
 * The v1 UI used the Material Symbols webfont. Brand Style Guide v2 mandates Lucide
 * (24px grid, 2px stroke, rounded). This map is the single translation table used by
 * `components/ui/Icon.jsx`, so pages can either pass a Lucide component directly or
 * keep the legacy glyph name during the migration.
 *
 * Keys are the exact `material-symbols-outlined` ligature strings found in the codebase.
 */
export const ICON_MAP = {
  account_balance_wallet: 'Wallet',
  arrow_back: 'ArrowLeft',
  arrow_forward: 'ArrowRight',
  article: 'FileText',
  attachment: 'Paperclip',
  badge: 'BadgeCheck',
  calculate: 'Calculator',
  calendar_clock: 'CalendarClock',
  calendar_month: 'CalendarDays',
  chat: 'MessageSquare',
  check: 'Check',
  check_circle: 'CircleCheck',
  chevron_left: 'ChevronLeft',
  chevron_right: 'ChevronRight',
  close: 'X',
  cloud_upload: 'CloudUpload',
  description: 'FileText',
  edit_calendar: 'CalendarPlus',
  emergency: 'Siren',
  error: 'CircleAlert',
  event_available: 'CalendarCheck',
  explore: 'Compass',
  filter_list: 'ListFilter',
  gavel: 'Gavel',
  group: 'Users',
  groups: 'Users',
  history: 'History',
  history_edu: 'GraduationCap',
  history_toggle_off: 'History',
  auto_stories: 'BookOpen',
  military_tech: 'Award',
  science: 'FlaskConical',
  translate: 'Languages',
  terminal: 'Terminal',
  person_search: 'UserSearch',
  wallet: 'Wallet',
  credit_card: 'CreditCard',
  account_balance: 'Landmark',
  group_add: 'UserPlus',
  forum_rounded: 'MessagesSquare',
  hourglass_top: 'Hourglass',
  info: 'Info',
  inventory: 'Package',
  inventory_2: 'Package',
  inbox: 'Inbox',
  wifi_off: 'WifiOff',
  search_off: 'SearchX',
  sync_problem: 'RefreshCcw',
  speed: 'Gauge',
  block: 'Ban',
  key: 'KeyRound',
  folder_open: 'FolderOpen',
  shopping_bag: 'ShoppingBag',
  cloud_off: 'CloudOff',
  person_off: 'UserX',
  do_not_disturb: 'Ban',
  mark_email_read: 'MailCheck',
  mark_email_unread: 'Mail',
  done_all: 'CheckCheck',
  sort: 'ArrowUpDown',
  swap_horiz: 'ArrowLeftRight',
  content_copy: 'Copy',
  print: 'Printer',
  download: 'Download',
  file_download: 'Download',
  file_upload: 'Upload',
  image: 'Image',
  photo_camera: 'Camera',
  mic: 'Mic',
  star_border: 'Star',
  star_half: 'StarHalf',
  favorite: 'Heart',
  thumb_up: 'ThumbsUp',
  thumb_down: 'ThumbsDown',
  sentiment_satisfied: 'Smile',
  sentiment_dissatisfied: 'Frown',
  celebration: 'PartyPopper',
  rocket_launch: 'Rocket',
  lightbulb: 'Lightbulb',
  construction: 'Construction',
  engineering: 'Wrench',
  support_agent: 'Headset',
  headset_mic: 'Headset',
  insights: 'TrendingUp',
  contact_support: 'LifeBuoy',
  question_answer: 'MessagesSquare',
  forum: 'MessagesSquare',
  comment: 'MessageCircle',
  textsms: 'MessageSquareText',
  email: 'Mail',
  call: 'Phone',
  videocam: 'Video',
  screen_share: 'ScreenShare',
  zoom_in: 'ZoomIn',
  zoom_out: 'ZoomOut',
  fullscreen: 'Maximize',
  fullscreen_exit: 'Minimize',
  keyboard_arrow_down: 'ChevronDown',
  keyboard_arrow_up: 'ChevronUp',
  keyboard_arrow_left: 'ChevronLeft',
  keyboard_arrow_right: 'ChevronRight',
  arrow_drop_down: 'ChevronDown',
  first_page: 'ChevronsLeft',
  last_page: 'ChevronsRight',
  navigate_before: 'ChevronLeft',
  navigate_next: 'ChevronRight',
  item: 'Box',
  location_on: 'MapPin',
  lock: 'Lock',
  lock_clock: 'LockKeyhole',
  login: 'LogIn',
  logout: 'LogOut',
  menu: 'Menu',
  menu_book: 'BookOpen',
  notifications: 'Bell',
  notifications_active: 'BellRing',
  notifications_off: 'BellOff',
  open_in_new: 'ExternalLink',
  payments: 'Banknote',
  pending_actions: 'Clock',
  person_add: 'UserPlus',
  pill: 'Pill',
  psychology: 'Brain',
  radio_button_checked: 'CircleDot',
  radio_button_unchecked: 'Circle',
  receipt: 'Receipt',
  receipt_long: 'ReceiptText',
  refresh: 'RefreshCw',
  savings: 'PiggyBank',
  school: 'GraduationCap',
  search: 'Search',
  send: 'Send',
  shield: 'ShieldCheck',
  space_dashboard: 'LayoutDashboard',
  star: 'Star',
  sync: 'RefreshCw',
  timeline: 'TrendingUp',
  timer: 'Timer',
  tune: 'SlidersHorizontal',
  verified: 'BadgeCheck',
  verified_user: 'ShieldCheck',
  video_camera_front: 'Video',
  add: 'Plus',
  add_card: 'CreditCard',
  add_circle: 'CirclePlus',
  assignment: 'ClipboardList',
  attach_file: 'Paperclip',
  autorenew: 'RefreshCw',
  campaign: 'Megaphone',
  cancel: 'XCircle',
  category: 'Tags',
  code: 'Code',
  currency_exchange: 'ArrowLeftRight',
  delete: 'Trash2',
  devices: 'Monitor',
  edit: 'Pencil',
  emoji_events: 'Award',
  error_outline: 'CircleAlert',
  expand_more: 'ChevronDown',
  expand_less: 'ChevronUp',
  event: 'Calendar',
  event_repeat: 'Repeat',
  fact_check: 'ClipboardCheck',
  filter_alt: 'ListFilter',
  flash_on: 'Zap',
  flag: 'Flag',
  folder: 'FolderOpen',
  help: 'CircleHelp',
  help_outline: 'CircleHelp',
  home: 'House',
  home_work: 'Building2',
  hourglass_empty: 'Hourglass',
  language: 'Languages',
  laptop_chromebook: 'Laptop',
  link: 'Link',
  list: 'List',
  local_library: 'BookOpen',
  mail: 'Mail',
  meeting_room: 'DoorOpen',
  more_vert: 'MoreVertical',
  open_in_full: 'Maximize2',
  pause_circle: 'CirclePause',
  person: 'User',
  phone: 'Phone',
  pie_chart: 'PieChart',
  play_arrow: 'Play',
  play_circle: 'PlayCircle',
  publish: 'Upload',
  published_with_changes: 'RefreshCw',
  rate_review: 'Star',
  remove: 'Minus',
  replay: 'RotateCcw',
  reply: 'Reply',
  report: 'Flag',
  report_problem: 'TriangleAlert',
  schedule: 'Clock',
  security: 'ShieldCheck',
  settings: 'Settings',
  task_alt: 'ClipboardCheck',
  trending_up: 'TrendingUp',
  unpublished: 'EyeOff',
  upload_file: 'Upload',
  visibility: 'Eye',
  visibility_off: 'EyeOff',
  warning: 'TriangleAlert',
  work: 'Briefcase',
  work_history: 'Briefcase',
};

/**
 * Resolve a legacy Material Symbols ligature name to its Lucide name.
 * Unknown names fall back to `CircleHelp` so a missing mapping is visible, not blank.
 *
 * LƯU Ý: fallback đó chỉ làm lộ lỗi, không phải lỗi chấp nhận được. Một tên thiếu
 * sẽ hiện dấu hỏi ở đúng chỗ người dùng định thấy một biểu tượng khác — dễ bỏ sót
 * hơn nhiều so với khoảng trống. Khi thêm tên mới, kiểm tra lại bằng:
 *   tìm mọi `<Icon name="...">` rồi so với key của ICON_MAP.
 */
export function resolveIconName(materialName) {
  if (!materialName) return 'CircleHelp';
  return ICON_MAP[materialName] ?? 'CircleHelp';
}

export default ICON_MAP;
