import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpDown,
  Award,
  BadgeCheck,
  Ban,
  Banknote,
  Bell,
  BellOff,
  BellRing,
  BookOpen,
  Box,
  Brain,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CirclePause,
  CirclePlus,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CloudOff,
  CloudUpload,
  Code,
  Compass,
  Construction,
  Copy,
  CreditCard,
  DoorOpen,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flag,
  FlaskConical,
  FolderOpen,
  Frown,
  Gauge,
  Gavel,
  GraduationCap,
  Headset,
  Heart,
  History,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Laptop,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  ListFilter,
  Lock,
  LockKeyhole,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MapPin,
  Maximize,
  Maximize2,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  MessagesSquare,
  Mic,
  Minimize,
  Minus,
  Monitor,
  MoreVertical,
  Package,
  Paperclip,
  PartyPopper,
  Pencil,
  Phone,
  PieChart,
  PiggyBank,
  Pill,
  Play,
  PlayCircle,
  Plus,
  Printer,
  Receipt,
  ReceiptText,
  RefreshCcw,
  RefreshCw,
  Reply,
  Repeat,
  Rocket,
  RotateCcw,
  ScreenShare,
  Search,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Siren,
  SlidersHorizontal,
  Smile,
  Star,
  StarHalf,
  Tags,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  UserPlus,
  Users,
  UserSearch,
  UserX,
  Video,
  Wallet,
  WifiOff,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

const REGISTRY = {
  ArrowLeft: ArrowLeft,
  ArrowLeftRight: ArrowLeftRight,
  ArrowRight: ArrowRight,
  ArrowUpDown: ArrowUpDown,
  Award: Award,
  BadgeCheck: BadgeCheck,
  Ban: Ban,
  Banknote: Banknote,
  Bell: Bell,
  BellOff: BellOff,
  BellRing: BellRing,
  BookOpen: BookOpen,
  Box: Box,
  Brain: Brain,
  Briefcase: Briefcase,
  Building2: Building2,
  Calculator: Calculator,
  Calendar: Calendar,
  CalendarCheck: CalendarCheck,
  CalendarClock: CalendarClock,
  CalendarDays: CalendarDays,
  CalendarPlus: CalendarPlus,
  Camera: Camera,
  Check: Check,
  CheckCheck: CheckCheck,
  ChevronDown: ChevronDown,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronsLeft: ChevronsLeft,
  ChevronsRight: ChevronsRight,
  ChevronUp: ChevronUp,
  Circle: Circle,
  CircleAlert: CircleAlert,
  CircleCheck: CircleCheck,
  CircleDot: CircleDot,
  CircleHelp: CircleHelp,
  CirclePause: CirclePause,
  CirclePlus: CirclePlus,
  ClipboardCheck: ClipboardCheck,
  ClipboardList: ClipboardList,
  Clock: Clock,
  CloudOff: CloudOff,
  CloudUpload: CloudUpload,
  Code: Code,
  Compass: Compass,
  Construction: Construction,
  Copy: Copy,
  CreditCard: CreditCard,
  DoorOpen: DoorOpen,
  Download: Download,
  ExternalLink: ExternalLink,
  Eye: Eye,
  EyeOff: EyeOff,
  FileText: FileText,
  Flag: Flag,
  FlaskConical: FlaskConical,
  FolderOpen: FolderOpen,
  Frown: Frown,
  Gauge: Gauge,
  Gavel: Gavel,
  GraduationCap: GraduationCap,
  Headset: Headset,
  Heart: Heart,
  History: History,
  Hourglass: Hourglass,
  House: House,
  Image: Image,
  Inbox: Inbox,
  Info: Info,
  KeyRound: KeyRound,
  Landmark: Landmark,
  Languages: Languages,
  Laptop: Laptop,
  LayoutDashboard: LayoutDashboard,
  LifeBuoy: LifeBuoy,
  Lightbulb: Lightbulb,
  Link: Link,
  List: List,
  ListFilter: ListFilter,
  Lock: Lock,
  LockKeyhole: LockKeyhole,
  LogIn: LogIn,
  LogOut: LogOut,
  Mail: Mail,
  MailCheck: MailCheck,
  MapPin: MapPin,
  Maximize: Maximize,
  Maximize2: Maximize2,
  Megaphone: Megaphone,
  Menu: Menu,
  MessageCircle: MessageCircle,
  MessageSquare: MessageSquare,
  MessageSquareText: MessageSquareText,
  MessagesSquare: MessagesSquare,
  Mic: Mic,
  Minimize: Minimize,
  Minus: Minus,
  Monitor: Monitor,
  MoreVertical: MoreVertical,
  Package: Package,
  Paperclip: Paperclip,
  PartyPopper: PartyPopper,
  Pencil: Pencil,
  Phone: Phone,
  PieChart: PieChart,
  PiggyBank: PiggyBank,
  Pill: Pill,
  Play: Play,
  PlayCircle: PlayCircle,
  Plus: Plus,
  Printer: Printer,
  Receipt: Receipt,
  ReceiptText: ReceiptText,
  RefreshCcw: RefreshCcw,
  RefreshCw: RefreshCw,
  Reply: Reply,
  Repeat: Repeat,
  Rocket: Rocket,
  RotateCcw: RotateCcw,
  ScreenShare: ScreenShare,
  Search: Search,
  SearchX: SearchX,
  Send: Send,
  Settings: Settings,
  ShieldCheck: ShieldCheck,
  ShoppingBag: ShoppingBag,
  Siren: Siren,
  SlidersHorizontal: SlidersHorizontal,
  Smile: Smile,
  Star: Star,
  StarHalf: StarHalf,
  Tags: Tags,
  Terminal: Terminal,
  ThumbsDown: ThumbsDown,
  ThumbsUp: ThumbsUp,
  Timer: Timer,
  Trash2: Trash2,
  TrendingUp: TrendingUp,
  TriangleAlert: TriangleAlert,
  Upload: Upload,
  User: User,
  UserPlus: UserPlus,
  Users: Users,
  UserSearch: UserSearch,
  UserX: UserX,
  Video: Video,
  Wallet: Wallet,
  WifiOff: WifiOff,
  Wrench: Wrench,
  X: X,
  XCircle: XCircle,
  Zap: Zap,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
};

export function getLucideIcon(name) {
  return REGISTRY[name] ?? REGISTRY.CircleHelp;
}

export default REGISTRY;
