/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        sm6: '6px',
        md10: '10px',
        lg16: '16px',
        xl24: '24px',
        '2xl32': '32px',
      },
      colors: {
        brand: {
          navy: {
            950: '#0B0F17',
            900: '#0F172A',
            800: '#1E293B',
          },
          indigo: {
            50: '#EEF2FF',
            100: '#E0E7FF',
            500: '#6366F1',
            600: '#4F46E5',
            700: '#4338CA',
          },
        },
        'brand-navy-950': '#0B0F17',
        'brand-navy-900': '#0F172A',
        'brand-navy-800': '#1E293B',
        'brand-indigo-50': '#EEF2FF',
        'brand-indigo-100': '#E0E7FF',
        'brand-indigo-500': '#6366F1',
        'brand-indigo-600': '#4F46E5',
        'brand-indigo-700': '#4338CA',

        // Stitch Semantic Escrow Colors
        'financial-available': '#10B981',
        'financial-available-strong': '#047857',
        'financial-available-bg': '#ECFDF5',
        'financial-holding': '#F59E0B',
        'financial-holding-bg': '#FFFBEB',
        'financial-dispute': '#EF4444',
        'financial-dispute-bg': '#FEF2F2',
        'financial-escrow-blue': '#3B82F6',
        'financial-escrow-blue-bg': '#EFF6FF',
        financial: {
          available: '#10B981',
          'available-strong': '#047857',
          'available-bg': '#ECFDF5',
          holding: '#F59E0B',
          'holding-bg': '#FFFBEB',
          dispute: '#EF4444',
          'dispute-bg': '#FEF2F2',
          escrow: '#3B82F6',
          'escrow-bg': '#EFF6FF',
        },

        // Surface & Glassmorphism Tokens
        'surface-card-glass': 'rgba(255, 255, 255, 0.85)',
        'surface-card-light': '#FFFFFF',
        'surface-canvas-light': '#F8FAFC',
        'border-light': '#E2E8F0',
        'text-primary': '#0F172A',
        'text-secondary': '#475569',
        'text-muted': '#94A3B8',

        // Stitch System Tokens
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'primary-fixed-dim': '#c3c0ff',
        'primary-fixed': '#e2dfff',
        'surface-tint': '#4d44e3',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#f0ecf9',
        'surface-container-high': '#eae6f4',
        'surface-container-highest': '#e4e1ee',
        'surface-container-lowest': '#ffffff',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'margin': '1.5rem',
        'gutter': '1rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        display: ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-1': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-2': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-3': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-reg': ['Inter', 'sans-serif'],
        'caption': ['Inter', 'sans-serif'],
        'monospace-num': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-hero': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-1': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-2': ['22px', { lineHeight: '1.35', fontWeight: '600' }],
        'headline-3': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-reg': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        'monospace-num': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
      },
      boxShadow: {
        'glass': '0 4px 20px -2px rgba(15, 23, 42, 0.05)',
        'glass-hover': '0 10px 25px -3px rgba(79, 70, 229, 0.12)',
        'card-glow': '0 0 25px -5px rgba(79, 70, 229, 0.15)',
        'premium': '0 20px 40px -15px rgba(15, 23, 42, 0.07)',
        'glow-indigo': '0 0 30px -5px rgba(79, 70, 229, 0.3)',
        'glow-emerald': '0 0 30px -5px rgba(16, 185, 129, 0.3)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 4s ease-in-out infinite',
        'fadeIn': 'fadeIn 0.25s ease-out forwards',
        'shake': 'shake 0.4s ease-in-out',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(4px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%, 60%': { transform: 'translateX(-4px)' },
          '40%, 80%': { transform: 'translateX(4px)' },
        },
      }
    },
  },
  plugins: [],
  corePlugins: {
    preflight: true,
  },
};
